variables:
   DOC_ROOT: $(Build.SourcesDirectory)/ACE_TAO
   ACE_ROOT: $(DOC_ROOT)/ACE
   MPC_ROOT: $(Build.SourcesDirectory)
   TAO_ROOT: $(DOC_ROOT)/TAO
   CIAO_ROOT: $(DOC_ROOT)/CIAO
   DAnCE_ROOT: $(Build.SourcesDirectory)/DAnCE
   DDS_ROOT: $(Build.SourcesDirectory)/DDS
   system.prefergit: true

schedules:
- cron: "0 7 * * SUN"
  displayName: Weekly Sunday
  branches:
    include:
    - master
  always: true

resources:
- repo: self
  fetchDepth: 1

jobs:
- job: VisualStudio2019
  timeoutInMinutes: 90
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      Debug64:
        BuildPlatform: x64
        BuildConfiguration: Debug
        vcpkgarch: x64-windows
        vcpkglibdir: debug\lib
        vcpkgpackages: openssl xerces-c
      Debug32:
        BuildPlatform: Win32
        BuildConfiguration: Debug
        vcpkgarch: x86-windows
        vcpkglibdir: debug\lib
        vcpkgpackages: openssl xerces-c
  variables:
    VCPKG_ROOT: $(Build.SourcesDirectory)\vcpkg
    XERCESC_INCDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\include
    XERCESC_LIBDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\$(vcpkglibdir)
    SSL_INCDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\include
    SSL_LIBDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\$(vcpkglibdir)
  steps:
  - powershell: |
      git clone -q --depth 1 git://github.com/Microsoft/vcpkg.git $(VCPKG_ROOT)
      $(VCPKG_ROOT)\bootstrap-vcpkg.bat
      $(VCPKG_ROOT)\vcpkg install --recurse --triplet $(vcpkgarch) $(vcpkgpackages)
    displayName: Install additional packages using vcpkg
  - powershell: |
      git clone -q --depth 1 git://github.com/DOCGroup/ACE_TAO.git $(Build.SourcesDirectory)/ACE_TAO
      git clone -q --depth 1 git://github.com/DOCGroup/DAnCE.git $(DAnCE_ROOT)
      git clone -q --depth 1 git://github.com/DOCGroup/CIAO.git $(CIAO_ROOT)
    displayName: git clone dependent repositories
  - powershell: |
      '#include "ace/config-win32.h"' > $(ACE_ROOT)\ace\config.h
    displayName: Create config.h file
  - powershell: |
      echo "xerces3=1" | out-file -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "ssl=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "openssl11=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
    displayName: Create default.features file
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type vs2019 $(CIAO_ROOT)/CIAO_TAO_DAnCE.mwc -workers 4
    displayName: Run script mwc.pl on $(CIAO_ROOT)/CIAO_TAO_DAnCE.mwc
  - task: VSBuild@1
    displayName: Build solution $(CIAO_ROOT)/CIAO_TAO_DAnCE.sln
    inputs:
      solution: $(CIAO_ROOT)/CIAO_TAO_DAnCE.sln
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      maximumCpuCount: true

- job: VisualStudio2017
  timeoutInMinutes: 90
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Release64:
        BuildPlatform: x64
        BuildConfiguration: Release
        vcpkgarch: x64-windows
        vcpkglibdir: lib
        vcpkgpackages: openssl xerces-c
  variables:
    VCPKG_ROOT: $(Build.SourcesDirectory)\vcpkg
    XERCESC_INCDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\include
    XERCESC_LIBDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\$(vcpkglibdir)
    SSL_INCDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\include
    SSL_LIBDIR: $(VCPKG_ROOT)\installed\$(vcpkgarch)\$(vcpkglibdir)
  steps:
  - powershell: |
      git clone -q --depth 1 git://github.com/Microsoft/vcpkg.git $(VCPKG_ROOT)
      $(VCPKG_ROOT)\bootstrap-vcpkg.bat
      $(VCPKG_ROOT)\vcpkg install --recurse --triplet $(vcpkgarch) $(vcpkgpackages)
    displayName: Install additional packages using vcpkg
  - powershell: |
      git clone -q --depth 1 git://github.com/DOCGroup/ACE_TAO.git $(Build.SourcesDirectory)/ACE_TAO
      git clone -q --depth 1 git://github.com/DOCGroup/DAnCE.git $(DAnCE_ROOT)
      git clone -q --depth 1 git://github.com/DOCGroup/CIAO.git $(CIAO_ROOT)
    displayName: git clone dependent repositories
  - powershell: |
      '#include "ace/config-win32.h"' > $(ACE_ROOT)\ace\config.h
    displayName: Create config.h file
  - powershell: |
      echo "xerces3=1" | out-file -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "ssl=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "openssl11=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
    displayName: Create default.features file
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type vs2017 $(CIAO_ROOT)/CIAO_TAO_DAnCE.mwc -workers 4
    displayName: Run script mwc.pl on $(CIAO_ROOT)/CIAO_TAO_DAnCE.mwc
  - task: VSBuild@1
    displayName: Build solution $(CIAO_ROOT)/CIAO_TAO_DAnCE.sln
    inputs:
      solution: $(CIAO_ROOT)/CIAO_TAO_DAnCE.sln
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      maximumCpuCount: true

- job: VisualStudio2015
  timeoutInMinutes: 90
  pool:
    vmImage: vs2015-win2012r2
  strategy:
    matrix:
      Release64:
        BuildPlatform: x64
        BuildConfiguration: Release
        vcpkgarch: x64-windows
        vcpkglibdir: lib
  variables:
    VCPKG_ROOT: $(Build.SourcesDirectory)\vcpkg
    XERCESCROOT: $(Build.SourcesDirectory)\vcpkg\packages\xerces-c_$(vcpkgarch)
    SSL_ROOT: $(Build.SourcesDirectory)\vcpkg\packages\openssl-windows_$(vcpkgarch)
    SSL_LIBDIR: $(SSL_ROOT)\$(vcpkglibdir)
    XERCESC_LIBDIR: $(XERCESCROOT)\$(vcpkglibdir)
  steps:
  - powershell: |
      git clone --depth 1 git://github.com/Microsoft/vcpkg.git $(VCPKG_ROOT)
      $(VCPKG_ROOT)\bootstrap-vcpkg.bat
      $(VCPKG_ROOT)\vcpkg.exe install --recurse --triplet $(vcpkgarch) openssl xerces-c
    displayName: vcpkg
  - powershell: |
      git clone -q --depth 1 git://github.com/DOCGroup/ACE_TAO.git $(Build.SourcesDirectory)/ACE_TAO
      git clone -q --depth 1 git://github.com/DOCGroup/DAnCE.git $(DAnCE_ROOT)
      git clone -q --depth 1 git://github.com/DOCGroup/CIAO.git $(CIAO_ROOT)
    displayName: git clone dependent repositories
  - powershell: |
      '#include "ace/config-win32.h"' > $(ACE_ROOT)\ace\config.h
    displayName: Create config.h file
  - powershell: |
      echo "xerces3=1" | out-file -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "ssl=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
      echo "openssl11=1" | out-file -append -encoding ASCII $(ACE_ROOT)\bin\MakeProjectCreator\config\default.features
    displayName: Create default.features file
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type vc14 $(CIAO_ROOT)/CIAO_TAO_DAnCE.mwc -workers 4
    displayName: Run script mwc.pl on $(CIAO_ROOT)/CIAO_TAO_DAnCE.mwc
  - task: VSBuild@1
    displayName: Build solution $(CIAO_ROOT)/CIAO_TAO_DAnCE.sln
    inputs:
      solution: $(CIAO_ROOT)/CIAO_TAO_DAnCE.sln
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      maximumCpuCount: true

- job: Linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      GCC9:
        CC: gcc-9
        CXX: g++-9
        PackageDeps: g++-9
        platform_file: include $(ACE_ROOT)/include/makeinclude/platform_linux.GNU
  steps:
  - script: |
      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ $(Repo) main"
    displayName: Add repository ($(Repo))
    condition: and(succeeded(), ne(variables['Repo'], ''))
  - script: |
      sudo apt-get --yes update
      sudo apt-get --yes install libxerces-c-dev libssl-dev $(PackageDeps)
    displayName: install system package dependencies ($(PackageDeps))
  - powershell: |
      git clone -q --depth 1 git://github.com/DOCGroup/ACE_TAO.git $(Build.SourcesDirectory)/ACE_TAO
      git clone -q --depth 1 git://github.com/DOCGroup/DAnCE.git $(DAnCE_ROOT)
      git clone -q --depth 1 git://github.com/DOCGroup/CIAO.git $(CIAO_ROOT)
      git clone -q --depth 1 git://github.com/objectcomputing/OpenDDS $(DDS_ROOT)
  - powershell: |
      '#include "ace/config-linux.h"' > $(ACE_ROOT)/ace/config.h
    displayName: Create config.h file
  - powershell: |
      'xerces3=1' > $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
      'dds4ccm_opendds=1' >> $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
      'dds_suppress_anys=0' >> $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
      'ssl=1' >> $(ACE_ROOT)/bin/MakeProjectCreator/config/default.features
    displayName: Create default.features file
  - powershell: |
      'c++11=1' > $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
      'xerces3=1' >> $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
      'ssl=1' >> $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
      'dds4ccm_opendds=1' >> $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
      "$(platform_file)" >> $(ACE_ROOT)/include/makeinclude/platform_macros.GNU
    displayName: Create platform_macros file
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type gnuace $(CIAO_ROOT)/CIAO_TAO_DAnCE_OpenDDS.mwc -workers 4
    displayName: Run mwc.pl on $(CIAO_ROOT)/CIAO_TAO_DAnCE_OpenDDS.mwc
  - bash: make -j 6 -C $(CIAO_ROOT)
    displayName: Build project

- job: MacOSX
  pool:
    vmImage: macOS-latest
  steps:
  - powershell: |
      git clone -q --depth 1 git://github.com/DOCGroup/ACE_TAO.git $(Build.SourcesDirectory)/ACE_TAO
      git clone -q --depth 1 git://github.com/DOCGroup/CIAO.git $(CIAO_ROOT)
      git clone -q --depth 1 git://github.com/DOCGroup/DAnCE.git $(DAnCE_ROOT)
  - powershell: |
      '#include "ace/config-macosx.h"' > $(ACE_ROOT)/ace/config.h
    displayName: Create config.h file
  - powershell: |
      'include $(ACE_ROOT)/include/makeinclude/platform_macosx.GNU' > $(ACE_ROOT)/include/makeinclude/platform_macros.GNU;
    displayName: Create platform_macros file
  - powershell: perl $(ACE_ROOT)/bin/mwc.pl -type gnuace $(CIAO_ROOT)/CIAO_TAO_DAnCE.mwc -workers 4
    displayName: Run mwc.pl on $(CIAO_ROOT)/CIAO_TAO_DAnCE.mwc
  - bash: make -j 6 -C $(CIAO_ROOT)
    displayName: Build project
