name: fuzz

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * SUN'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DOC_ROOT: ${{ github.workspace }}/ACE
  ACE_ROOT: ${{ github.workspace }}/ACE/ACE
  TAO_ROOT: ${{ github.workspace }}/ACE/TAO

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout MPC
      uses: actions/checkout@v4
    - name: checkout ACE_TAO
      uses: actions/checkout@v4
      with:
        repository: DOCGroup/ACE_TAO
        path: ${{ env.DOC_ROOT }}
    - name: Run fuzz
      run: |
        perl ${env:ACE_ROOT}/bin/fuzz.pl
      shell: pwsh
